# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-26 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.CharField(blank='True', max_length=25, primary_key='True', serialize=False)),
                ('business', models.CharField(db_index=True, max_length=150)),
                ('point_of_contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('business_phone_number', models.IntegerField(null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('industry', models.IntegerField(choices=[(1, 'fuel'), (2, 'nondurable manfacturer'), (3, 'tech'), (4, 'retail'), (5, 'wholesale trade'), (6, 'state_military_federal'), (7, 'other')])),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('other_details', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOrder',
            fields=[
                ('MISC', models.TextField(blank=True)),
                ('order_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('service_type', models.IntegerField(choices=[(0, 'pickup'), (1, 'delivery')], null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=500, null=True)),
                ('distance_from_company_to_business', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hazmat_class', models.IntegerField(choices=[(1, 'Non-hazard'), (2, 'Explosive'), (3, 'Gases'), (4, 'Flammable Liquid'), (5, 'Combustible Liquid'), (6, 'Flammable Solid'), (7, 'Spontanaeously Combustible'), (8, 'Dangerous When Wet'), (10, 'Oxidizer and Organic Peroxide'), (11, 'Poison (Toxic) and Poison Inhalation Hazard'), (12, 'Radioactive'), (models.TextField(blank=True), 'Miscellaneous, and the general Dangerous placard')], null=True)),
                ('business_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessorders_business_id_set', to='wdapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.CharField(blank='True', max_length=25, primary_key='True', serialize=False)),
                ('cargo', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('category', models.IntegerField(choices=[(1, 'fuel'), (2, 'manfacturer'), (3, 'tech'), (4, 'retail'), (5, 'perishable'), (6, 'state_military_federal'), (7, 'other')], null=True)),
                ('state_of_matter', models.IntegerField(choices=[(1, 'liquid'), (2, 'solid'), (3, 'gas'), (4, 'plasma')], null=True)),
                ('weight', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('short_description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoManifest',
            fields=[
                ('manifest_id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('estimated_trip_distance', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_adress_set', to='wdapp.BusinessOrder')),
                ('cargo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_cargo_id_set', to='wdapp.BusinessOrder')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_company_id_set', to='wdapp.BusinessOrder')),
                ('date_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_date_created_set', to='wdapp.BusinessOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(blank='True', max_length=25, primary_key='True', serialize=False)),
                ('company', models.CharField(max_length=500, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=500, null=True)),
                ('trucking_specilization', models.CharField(choices=[('Fuel', 'fuel'), ('Manfacturer', 'nondurable manfacturer'), ('Technology', 'tech'), ('Retail', 'retail'), ('Wholesale', 'wholesale trade'), ('Goverment', 'Goverment'), ('Other', 'other')], max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('year_established', models.DateField(max_length=500, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company_data',
            fields=[
                ('c_data_id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('revenue', models.IntegerField(null=True)),
                ('other_details', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_set', to='wdapp.Company')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_company_set', to='wdapp.Company')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_date_set', to='wdapp.BusinessOrder')),
                ('price_for_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_price_for_service_price_set', to='wdapp.BusinessOrder')),
                ('trucking_specilization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_trucking_specialty_set', to='wdapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(blank='True', max_length=25, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(null=True)),
                ('ssn', models.CharField(db_index=True, max_length=9, null=True)),
                ('wage_plan', models.CharField(choices=[('Hourly', 'hourly'), ('Miles', 'miles')], max_length=50, null=True)),
                ('license', models.IntegerField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], null=True)),
                ('other_license', models.IntegerField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], null=True)),
                ('license_number', models.IntegerField(null=True)),
                ('date_hired', models.DateField(null=True)),
                ('location', models.CharField(max_length=9, null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_company_id_set', to='wdapp.Company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverExpense',
            fields=[
                ('expenses_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('expense_type', models.IntegerField(choices=[(1, 'fuel'), (2, 'meal'), (3, 'emergency'), (4, 'other')], null=True)),
                ('amount_of_expense', models.IntegerField(default=0, null=True)),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverexpenses_driver_id_set', to='wdapp.CargoManifest')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_adress_set', to='wdapp.BusinessOrder')),
                ('business_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_business_id_set', to='wdapp.BusinessOrder')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_cargo_set', to='wdapp.BusinessOrder')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_company_id_set', to='wdapp.BusinessOrder')),
                ('date_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_date_created_set', to='wdapp.BusinessOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(blank='True', max_length=25, primary_key='True', serialize=False)),
                ('stop_type', models.IntegerField(choices=[(1, 'fuel'), (2, 'meal'), (3, 'restroom'), (4, 'lodging'), (5, 'accident'), (6, 'other')], null=True)),
                ('stop_location', models.CharField(max_length=100, null=True)),
                ('time_stop', models.TimeField(auto_now_add=True)),
                ('departed_stop', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('trailer_license', models.CharField(max_length=7, null=True)),
                ('beginnning_weather_conditions', models.IntegerField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], default=1, null=True)),
                ('midway_weather_conditions', models.IntegerField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], default=1, null=True)),
                ('ending_weather_conditions', models.IntegerField(choices=[(1, 'normal'), (2, 'cloudy'), (3, 'rain'), (4, 'snow'), (5, 'hazardous'), (6, 'extremly hazardous')], default=1, null=True)),
                ('fuel_card_usage', models.IntegerField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes', null=True)),
                ('average_price_per_gallon', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gallons_of_gas_used', models.IntegerField(null=True)),
                ('number_of_unscheduled', models.IntegerField(null=True)),
                ('total_miles_traveled', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('order_details', models.TextField(null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_company_id_set', to='wdapp.CargoManifest')),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_driver_id_set', to='wdapp.CargoManifest')),
                ('estimated_trip_distance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimated_distance_set', to='wdapp.CargoManifest')),
                ('manifest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_manifest_id_set', to='wdapp.CargoManifest')),
                ('order_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_order_created_set', to='wdapp.CargoManifest')),
            ],
        ),
        migrations.AddField(
            model_name='stop',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_driver_id_set', to='wdapp.Trip'),
        ),
        migrations.AddField(
            model_name='stop',
            name='trip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_trip_id_set', to='wdapp.Trip'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_location_set', to='wdapp.Trip'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_name_set', to='wdapp.Trip'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_order_id_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_quanity_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_service_type_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='driverexpense',
            name='stop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverexpenses_stop_id_set', to='wdapp.Stop'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_driver_id_set', to='wdapp.Driver'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='hazmat_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifest_hazmat_class_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_location_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_order_id_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_point_of_contact_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_quantity_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_service_type_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_volume_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargomanifests_weight_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_set', to='wdapp.Cargo'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_set', to='wdapp.Company'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_set', to='wdapp.Cargo'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_set', to='wdapp.Cargo'),
        ),
        migrations.AddField(
            model_name='businessorder',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_set', to='wdapp.Cargo'),
        ),
    ]
