# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-26 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessorder',
            name='price',
        ),
        migrations.AddField(
            model_name='driver',
            name='other_license_2',
            field=models.IntegerField(choices=[('A', 'class a'), ('B', 'class b'), ('C', 'class c')], null=True),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_id_set', to='wdapp.Business'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_id', to='wdapp.Company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(max_length=25, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderstatus_address_set', to='wdapp.BusinessOrder'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdapp.BusinessOrder'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o_c_id_set', to='wdapp.BusinessOrder'),
        ),
    ]
