# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-27 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0002_auto_20181126_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company_data',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company_data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='company_data',
            name='price_for_service',
        ),
        migrations.RemoveField(
            model_name='company_data',
            name='trucking_specilization',
        ),
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_phone_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='created',
        ),
        migrations.RemoveField(
            model_name='business',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='business',
            name='point_of_contact',
        ),
        migrations.RemoveField(
            model_name='business',
            name='state',
        ),
        migrations.RemoveField(
            model_name='businessorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cargomanifest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cargomanifest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cargomanifest',
            name='point_of_contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='location',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='stop_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.CharField(max_length=25, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=9, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_id', to='wdapp.Company'),
        ),
        migrations.DeleteModel(
            name='Company_data',
        ),
    ]
