# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdapp', '0004_auto_20181127_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessorder',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargomanifest',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverexpense',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.CharField(max_length=25, null='True'),
        ),
        migrations.AlterField(
            model_name='businessorder',
            name='order_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_id',
            field=models.CharField(blank='True', max_length=25, null='True'),
        ),
        migrations.AlterField(
            model_name='cargomanifest',
            name='manifest_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=9, null='True'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(max_length=25, null='True'),
        ),
        migrations.AlterField(
            model_name='driverexpense',
            name='expenses_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(blank='True', max_length=25, null='True'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.IntegerField(null=True),
        ),
    ]
